### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by taldr27** [Full-Stack-Capstone/petbnb-back#5]
### Our team is the 4 people: @gandradep @erickhansx @tiagomarin @taldr27.
![image](https://user-images.githubusercontent.com/107952724/222493678-9d10c540-6ff5-4ac1-a33a-5954331f9e35.png)
### Link to our [FrontEnd](https://github.com/Full-Stack-Capstone/petbnb-front).

**Comment by Meltrust** [comment]
Hi @taldr27,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks have been assigned✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] Kindly, add a description to this task in order to meet the [requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md):

![image](https://user-images.githubusercontent.com/57421823/222495068-692e259c-0f77-4d45-a280-f307a6a4e2ac.png)



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
Hi @taldr27,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!





Congratulations! 🎉 

### To highlight

- All tasks have descriptions now✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by taldr27** [comment]
@Meltrust Thank you for reviewing our kanban board! 👌
